/** @file gem/base/exception/Exception.h */

#ifndef GEM_BASE_EXCEPTION_EXCEPTION_H
#define GEM_BASE_EXCEPTION_EXCEPTION_H

#include "gem/utils/exception/Exception.h"

// The gem::base exceptions.
#define GEM_BASE_DEFINE_EXCEPTION(EXCEPTION_NAME) GEM_DEFINE_EXCEPTION(EXCEPTION_NAME, base)
GEM_BASE_DEFINE_EXCEPTION(Exception)
GEM_BASE_DEFINE_EXCEPTION(ConfigurationParseProblem)
GEM_BASE_DEFINE_EXCEPTION(ConfigurationProblem)
GEM_BASE_DEFINE_EXCEPTION(ConfigurationValidationProblem)

GEM_BASE_DEFINE_EXCEPTION(HardwareProblem)

GEM_BASE_DEFINE_EXCEPTION(RCMSNotificationError)
GEM_BASE_DEFINE_EXCEPTION(SOAPTransitionProblem)

GEM_BASE_DEFINE_EXCEPTION(SoftwareProblem)
GEM_BASE_DEFINE_EXCEPTION(TransitionProblem)
GEM_BASE_DEFINE_EXCEPTION(ValueError)

// The gem::base alarms.
#define GEM_BASE_DEFINE_ALARM(ALARM_NAME) GEM_BASE_DEFINE_EXCEPTION(ALARM_NAME)
GEM_BASE_DEFINE_ALARM(MonitoringFailureAlarm)

#endif  // GEM_BASE_EXCEPTION_EXCEPTION_H
