#include <memory>

#include "gem/onlinedb/VFAT3ChipConfiguration.h"
#include "gem/onlinedb/SerializationData.h"

#define BOOST_TEST_DYN_LINK
#define BOOST_TEST_MODULE SerializationData
#include <boost/test/unit_test.hpp>

/* Needed to make the linker happy. */
#include <xdaq/version.h>
config::PackageInfo xdaq::getPackageInfo()
{
    return config::PackageInfo("", "", "", "", "", "", "", "", "");
}

using namespace gem::onlinedb;

BOOST_AUTO_TEST_SUITE(Serialization)

SerializationData<VFAT3ChipConfiguration> createTestSerializationData()
{
    SerializationData<VFAT3ChipConfiguration> builder;

    Run r;
    r.location = "Brussels";
    r.initiatingUser = "lmoureau";
    builder.setRun(r);

    DataSet<VFAT3ChipConfiguration> ds;
    ds.setComment("Test data generated by cmsgemos");
    ds.setVersion("pre-alpha");
    ds.setPart(PartReferenceBarcode{ "0/0" });
    ds.addData(VFAT3ChipConfiguration());
    ds.addData(VFAT3ChipConfiguration());
    builder.addDataSet(ds);

    return builder;
}

BOOST_AUTO_TEST_CASE(ToJSON)
{
    auto data = createTestSerializationData();
    nlohmann::json json = data;

    BOOST_CHECK(json["Root"]["Header"]["Run"]["InitiatedByUser"] == "lmoureau");
    BOOST_CHECK(json["Root"]["Datasets"][0]["Dataset"]["Data"].size() == 2);
}

BOOST_AUTO_TEST_CASE(JSONRoundTrip)
{
    auto data = createTestSerializationData();
    nlohmann::json json = data;
    auto roundTrip = json.get<SerializationData<VFAT3ChipConfiguration>>();
    BOOST_CHECK(data == roundTrip);
}

BOOST_AUTO_TEST_SUITE_END()
