/** @file gem/base/utils/exceptionException.h */

#ifndef GEM_BASE_UTILS_EXCEPTION_EXCEPTION_H
#define GEM_BASE_UTILS_EXCEPTION_EXCEPTION_H

#include "gem/utils/exception/Exception.h"

// The gem::base::utils exceptions.
#define GEM_BASE_UTILS_DEFINE_EXCEPTION(EXCEPTION_NAME) GEM_DEFINE_EXCEPTION(EXCEPTION_NAME, base::utils)
GEM_BASE_UTILS_DEFINE_EXCEPTION(Exception)
GEM_BASE_UTILS_DEFINE_EXCEPTION(CfgParseProblem)
GEM_BASE_UTILS_DEFINE_EXCEPTION(CfgProblem)
GEM_BASE_UTILS_DEFINE_EXCEPTION(CfgValidationProblem)

GEM_BASE_UTILS_DEFINE_EXCEPTION(RCMSNotificationError)
GEM_BASE_UTILS_DEFINE_EXCEPTION(SOAPTransitionProblem)

GEM_BASE_UTILS_DEFINE_EXCEPTION(InfoSpaceProblem)

GEM_BASE_UTILS_DEFINE_EXCEPTION(SoftwareProblem)
GEM_BASE_UTILS_DEFINE_EXCEPTION(TransitionProblem)
GEM_BASE_UTILS_DEFINE_EXCEPTION(ValueError)

// The gem::base::utils alarms.
#define GEM_BASE_UTILS_DEFINE_ALARM(ALARM_NAME) GEM_BASE_UTILS_DEFINE_EXCEPTION(ALARM_NAME)

GEM_BASE_UTILS_DEFINE_ALARM(MonitoringFailureAlarm)

#endif  // GEM_BASE_UTILS_EXCEPTION_EXCEPTION_H
